services:
  transaction-service:
    build:
      context: ../Transaction-service  # Points to folder
      dockerfile: Dockerfile     # Explicitly name the file
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://transaction-db:3306/paytm_transactiondb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - transaction-db

  transaction-db:
    image: mysql:8.0
    restart: always
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: paytm_transactiondb
    volumes:
      - transactiondb:/var/lib/mysql

volumes:
  transactiondb: